spring.application.name=honeypot

# DB 연결
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/honeypot?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=1111

# MyBatis
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.type-aliases-package=org.cloud.honeypot.dto
mybatis.configuration.map-underscore-to-camel-case=true

# Thymeleaf
spring.thymeleaf.cache=false

# SQL 로그
logging.level.org.cloud.honeypot.mapper=DEBUG